name: Portal CI

on: [push, pull_request]

env:
  TESTS_TIMEOUT: 10 # in minutes

jobs:
  check:
    name: Ubuntu 22.04 build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: ['gcc', 'clang']
        sanitizer: ['address']

    env:
      DEBIAN_FRONTEND: noninteractive
      BASE_CFLAGS: -Wp,-D_FORTIFY_SOURCE=2

    steps:
    - name: Check out xdg-desktop-portal
      uses: actions/checkout@v3

    - name: Build xdg-desktop-portal on Ubuntu
      uses: ./.github/actions/build-ubuntu
      with:
        ubuntuVersion: '22.04'
        compiler: ${{ matrix.compiler }}
        sanitizer: ${{ matrix.sanitizer }}
        buildDirectory: builddir
        runCommand: docker exec -t -w /src -e TEST_IN_CI -e ASAN_OPTIONS -e G_MESSAGES_DEBUG -e XDG_DATA_DIRS ${{ matrix.compiler }}-build-container
        runAsUserCommand: runuser -u tester --

    - name: Upload test logs
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: test logs
        path: |
          tests/*.log
          test-*.log
          installed-test-logs/
          builddir/meson-logs/testlog.txt
